export const Name='Testing-app'
export const Server='https://pulse-b.herokuapp.com'
export const IOServer='https://pulse-b.herokuapp.com'
export const Server1='http://192.168.1.6'
export const Port='3030'